'use strict';
const CFG=window.SEGGI_CONFIG||{};const BACKEND=String(CFG.backendUrl||'');const TOKEN_KEY='seggi_dashboard_token',EXP_KEY='seggi_dashboard_token_expiry';
let dashboardToken=sessionStorage.getItem(TOKEN_KEY)||'',live=null,registry={sezioni:[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const fmt=n=>Number(n||0).toLocaleString('it-IT');const pct=n=>(n===''||n==null)?'—':Number(n).toLocaleString('it-IT',{maximumFractionDigits:1})+'%';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function post(payload){const r=await fetch(BACKEND,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(payload),cache:'no-store'});if(!r.ok)throw new Error('Backend non raggiungibile ('+r.status+')');return r.json()}
function setOnline(ok,text){$('#connectionDot').classList.toggle('online',ok);$('#connectionText').textContent=text}
function showLogin(message=''){clearSession();$('#loginView').hidden=false;$('#appView').hidden=true;$('#loginError').textContent=message;['refreshBtn','printBtn','logoutBtn'].forEach(id=>$('#'+id).hidden=true);setOnline(false,'Non collegato')}
function clearSession(){dashboardToken='';sessionStorage.removeItem(TOKEN_KEY);sessionStorage.removeItem(EXP_KEY)}
async function login(password){const x=await post({tipo:'dashboard_login',password});if(!x.ok)throw new Error(x.error||'Accesso non riuscito');dashboardToken=x.dashboardToken;sessionStorage.setItem(TOKEN_KEY,dashboardToken);sessionStorage.setItem(EXP_KEY,x.expiresAt||'')}
async function loadRegistry(){registry=await fetch('data/sezioni-ix-control.json',{cache:'no-store'}).then(r=>r.json())}
async function load(){if(!dashboardToken)return showLogin();setOnline(false,'Aggiornamento…');try{const x=await post({tipo:'dashboard_affluenza',dashboardToken});if(!x.ok){if(String(x.code).includes('SESSION'))return showLogin(x.error);throw new Error(x.error||'Errore backend')}live=x;renderAll();$('#loginView').hidden=true;$('#appView').hidden=false;['refreshBtn','printBtn','logoutBtn'].forEach(id=>$('#'+id).hidden=false);setOnline(true,'Online');$('#backendVersion').textContent='Backend '+(x.versioneBackend||'-');$('#lastUpdate').textContent='Aggiornato '+new Date(x.serverTime).toLocaleString('it-IT')}catch(e){setOnline(false,'Errore');if(!live)showLogin(e.message);console.error(e)}}
function summary(level){return (live.riepilogoFdi||{})[level]||{}}
function renderAll(){const t=live.totali||{},expected=Number(live.sezioniAttese||registry.sezioniTotali||0),received=Number(live.sezioniRicevute||0),progress=expected?received/expected*100:0;$('#kpiExpected').textContent=fmt(expected);$('#kpiReceived').textContent=fmt(received);$('#kpiProgress').textContent=pct(progress)+' completato';$('#kpiTurnout').textContent=pct(t.percentuale);$('#kpiVoters').textContent=fmt(t.totale)+' votanti';const scrSections=new Set((live.risultatiListe||[]).map(x=>x.municipio+'|'+x.sezione));$('#kpiScrutini').textContent=fmt(scrSections.size);const c=summary('Comune'),m=summary('Municipio');$('#kpiFdiComune').textContent=fmt(c.fdiVoti);$('#kpiFdiComunePct').textContent=pct(c.fdiSuValidi)+' sui validi';$('#kpiFdiMunicipio').textContent=fmt(m.fdiVoti);$('#kpiFdiMunicipioPct').textContent=pct(m.fdiSuValidi)+' sui validi';$('#progressBar').style.width=Math.min(100,progress)+'%';$('#progressLabel').textContent=pct(progress);$('#legendReceived').textContent=fmt(received);$('#legendMissing').textContent=fmt(live.sezioniMancanti);$('#missingBadge').textContent=fmt(live.sezioniMancanti);renderRecent();renderMissing();renderRankings($('#rankLevel').value,'#topList',5,false);renderRegistry();renderMapList();}
function renderRecent(){const rows=(live.ultimiInvii||[]).slice(0,7);$('#recentList').innerHTML=rows.map(r=>`<div class="recent-row"><i class="status-dot"></i><div><strong>Sezione ${esc(r.sezione)}</strong><small>${esc(r.giorno)} ${esc(r.orario)}</small></div><span>${r.percentuale===''?'—':pct(r.percentuale)}</span></div>`).join('')||'<p>Nessun invio.</p>'}
function renderMissing(){const rows=live.mancanti||[];$('#missingList').innerHTML=rows.slice(0,40).map(r=>`<button class="chip" data-section="${esc(r.sezione)}">${esc(r.sezione)}</button>`).join('')||'<span class="state done">Tutte le sezioni ricevute</span>';$$('#missingList [data-section]').forEach(b=>b.onclick=()=>openSection(b.dataset.section))}
function rankingRows(level){return (live.risultatiListe||[]).filter(x=>x.livello===level&&x.municipio==='09').sort((a,b)=>Number(b.fdiSuValidi||0)-Number(a.fdiSuValidi||0))}
function renderRankings(level,target,count=10,reverse=false){let rows=rankingRows(level);if(reverse)rows=rows.slice().reverse();rows=rows.slice(0,count);$(target).innerHTML=rows.map((r,i)=>`<div class="ranking-row" data-section="${esc(r.sezione)}"><span class="ranking-index">${i+1}</span><div><strong>Sezione ${esc(r.sezione)}</strong><small>${fmt(r.fdiVoti)} voti FdI</small></div><span class="ranking-value">${pct(r.fdiSuValidi)}</span></div>`).join('')||'<p>Nessun scrutinio disponibile.</p>';$$(`${target} [data-section]`).forEach(x=>x.onclick=()=>openSection(x.dataset.section))}
function statusFor(section){const sec=String(Number(section));const scr=(live.risultatiListe||[]).some(x=>String(Number(x.sezione))===sec);if(scr)return{label:'Scrutinio ricevuto',cls:'done'};const aff=(live.sezioni||[]).some(x=>String(Number(x.sezione))===sec);return aff?{label:'Affluenza ricevuta',cls:'done'}:{label:'Mancante',cls:'missing'}}
function filteredRegistry(q){q=String(q||'').trim().toLowerCase();return registry.sezioni.filter(x=>!q||x.sezione.includes(q)||x.indirizzo.toLowerCase().includes(q))}
function renderRegistry(){const rows=filteredRegistry($('#sectionSearch')?.value);$('#registrySummary').textContent=`${registry.sezioniTotali} sezioni in ${registry.plessiTotali} plessi elettorali`;$('#sectionsBody').innerHTML=rows.map(r=>{const st=statusFor(r.sezione);return`<tr data-section="${r.sezione}"><td><strong>${r.sezione}</strong></td><td>${esc(r.indirizzo)}</td><td>${esc(r.cap)}</td><td>${fmt(r.numeroVie)}</td><td><span class="state ${st.cls}">${st.label}</span></td></tr>`}).join('');$$('#sectionsBody tr').forEach(x=>x.onclick=()=>openSection(x.dataset.section))}
function renderMapList(){const rows=filteredRegistry($('#mapSearch')?.value).slice(0,175);$('#mapSectionList').innerHTML=rows.map(r=>{const st=statusFor(r.sezione);return`<div class="map-section-card" data-section="${r.sezione}"><strong>Sezione ${r.sezione}</strong><small>${esc(r.indirizzo)} · <span class="state ${st.cls}">${st.label}</span></small></div>`}).join('');$$('.map-section-card').forEach(x=>x.onclick=()=>openSection(x.dataset.section))}
function openSection(section){const reg=registry.sezioni.find(x=>String(Number(x.sezione))===String(Number(section)));const aff=(live.sezioni||[]).find(x=>String(Number(x.sezione))===String(Number(section)));const results=(live.risultatiListe||[]).filter(x=>String(Number(x.sezione))===String(Number(section)));const comune=results.find(x=>x.livello==='Comune'),municipio=results.find(x=>x.livello==='Municipio');$('#sectionDialogContent').innerHTML=`<p class="eyebrow">DETTAGLIO SEZIONE</p><h2>Sezione ${esc(section)}</h2><p><strong>${esc(reg?.indirizzo||'Indirizzo non disponibile')}</strong><br>${esc(reg?.cap||'')}</p><div class="report-grid"><div class="report-stat"><span>Affluenza</span><strong>${pct(aff?.percentuale)}</strong></div><div class="report-stat"><span>Votanti</span><strong>${fmt(aff?.totale||comune?.votanti)}</strong></div><div class="report-stat"><span>FdI Comune</span><strong>${fmt(comune?.fdiVoti)}</strong><small>${pct(comune?.fdiSuValidi)}</small></div><div class="report-stat"><span>FdI Municipio</span><strong>${fmt(municipio?.fdiVoti)}</strong><small>${pct(municipio?.fdiSuValidi)}</small></div></div><h3>Vie assegnate (${fmt(reg?.numeroVie)})</h3><p>${(reg?.vieAssegnate||[]).slice(0,20).map(esc).join(', ')||'—'}</p>`;$('#sectionDialog').showModal()}
function generateReport(){const c=summary('Comune'),m=summary('Municipio'),top=rankingRows('Comune').slice(0,10);$('#reportPreview').innerHTML=`<div class="report-sheet"><div class="report-title"><p class="eyebrow">RETE SEGGI FDI - IX MUNICIPIO ROMA</p><h2>Dossier elettorale - Elezioni amministrative</h2><p>Generato il ${new Date().toLocaleString('it-IT')}</p></div><div class="report-grid"><div class="report-stat"><span>Sezioni attese</span><strong>${fmt(live.sezioniAttese)}</strong></div><div class="report-stat"><span>Sezioni ricevute</span><strong>${fmt(live.sezioniRicevute)}</strong></div><div class="report-stat"><span>Affluenza</span><strong>${pct(live.totali?.percentuale)}</strong></div><div class="report-stat"><span>Votanti</span><strong>${fmt(live.totali?.totale)}</strong></div><div class="report-stat"><span>FdI Comune</span><strong>${fmt(c.fdiVoti)}</strong><small>${pct(c.fdiSuValidi)}</small></div><div class="report-stat"><span>FdI Municipio</span><strong>${fmt(m.fdiVoti)}</strong><small>${pct(m.fdiSuValidi)}</small></div><div class="report-stat"><span>Plessi</span><strong>${fmt(registry.plessiTotali)}</strong></div><div class="report-stat"><span>Sezioni mancanti</span><strong>${fmt(live.sezioniMancanti)}</strong></div></div><div class="report-table"><h3>Top 10 sezioni FdI - Comune</h3><table><thead><tr><th>Pos.</th><th>Sezione</th><th>Voti FdI</th><th>% validi</th><th>Indirizzo</th></tr></thead><tbody>${top.map((r,i)=>{const reg=registry.sezioni.find(x=>String(Number(x.sezione))===String(Number(r.sezione)));return`<tr><td>${i+1}</td><td>${esc(r.sezione)}</td><td>${fmt(r.fdiVoti)}</td><td>${pct(r.fdiSuValidi)}</td><td>${esc(reg?.indirizzo||'')}</td></tr>`}).join('')}</tbody></table></div></div>`}
function switchView(name){$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+name));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));if(name==='rankings'){renderRankings($('#rankingLevel').value,'#bestRankings',15,false);renderRankings($('#rankingLevel').value,'#worstRankings',15,true)}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';try{await login($('#password').value);$('#password').value='';await load()}catch(err){$('#loginError').textContent=err.message}});$('#refreshBtn').onclick=load;$('#logoutBtn').onclick=()=>showLogin();$('#printBtn').onclick=()=>{switchView('report');generateReport();setTimeout(()=>window.print(),100)};$('#generateReportBtn').onclick=generateReport;$('#closeDialog').onclick=()=>$('#sectionDialog').close();$$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-view-link]').forEach(b=>b.onclick=()=>switchView(b.dataset.viewLink));$('#rankLevel').onchange=e=>renderRankings(e.target.value,'#topList',5,false);$('#rankingLevel').onchange=e=>{renderRankings(e.target.value,'#bestRankings',15,false);renderRankings(e.target.value,'#worstRankings',15,true)};$('#sectionSearch').oninput=renderRegistry;$('#mapSearch').oninput=renderMapList;
(async()=>{await loadRegistry();if(dashboardToken)await load();else showLogin()})();
